name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  MathMLCan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - uses: actions/checkout@v2
      with:
        repository: MIR-MU/MathMLCan
    - run: mvn clean install
    - run: mvn integration-test
    - uses: actions/upload-artifact@v2
      with:
        name: MathMLCan
        path: .
  log4jwebtracker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - uses: actions/checkout@v2
      with:
        repository: mrsarm/log4jwebtracker
        ref: log4jwebtracker-1.0.1
    - run: mvn clean install
    - run: mvn integration-test
    - uses: actions/upload-artifact@v2
      with:
        name: log4jwebtracker
        path: .
  MathMLCanEval:
    needs: [MathMLCan, log4jwebtracker]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - uses: actions/download-artifact@v2
      with:
        name: MathMLCan
        path: MathMLCan
    - run: mvn install -f MathMLCan/pom.xml
    - uses: actions/download-artifact@v2
      with:
        name: log4jwebtracker
        path: log4jwebtracker
    - run: mvn install -f log4jwebtracker/pom.xml
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: mvn clean install
    - run: mvn integration-test
    - uses: actions/upload-artifact@v2
      with:
        name: MathMLCanEval
        path: .
